import Footer from "../components/Footer/Footer";
import Navbar from "../components/Header/Navbar";
import "./globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="header-footer-container">
          <header>
            <Navbar logoSrc={"/logo-dark.png"} brightLinks={false}/>
          </header>
          <main>
            {children}
          </main>
        </div>
        <footer>
            <Footer/>
        </footer>
      </body>
    </html>
  );
}
