import HamburgerMenu from "@/components/Main/HamburgerMenu";
import Navbar from "../components/Header/Navbar";
import "./globals.scss";
import AppContextProvider from "@/context/context";
import Overlay from "@/components/Main/Overlay";
import FooterParent from "@/components/Footer/FooterParent";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body>
      <AppContextProvider>
        <header>
          <Navbar logoSrc={"/logo-dark.png"} isHeader={true} brightLinks={false} hideOnMobile={true}/>
        </header>
        <div className="header-footer-container">
            <HamburgerMenu/>
            <Overlay/>
          <main>
            {children}
          </main>
        <footer>
            <FooterParent/>
        </footer>
        </div>
        </AppContextProvider>
      </body>
    </html>
  );
}
